#!/bin/bash
# Build NPU kernels for GGNPU
# Requires mlir-aie and Peano toolchains
#
# Usage:
#   ./scripts/build-kernels.sh              # Build with available tools
#   AIE_HOME=/path/to/mlir-aie ./scripts/build-kernels.sh
#   PEANO_HOME=/path/to/peano ./scripts/build-kernels.sh

set -euo pipefail

CACHE_DIR="${GGNPU_CACHE_DIR:-$HOME/.cache/ggnpu}"
XCLBIN_DIR="$CACHE_DIR/xclbin"
KERNELS_SRC="$PWD/kernels/amd/matmul_i8"

# NPU profiles (Krackan = npu6, Strix Point = npu4/npu5)
NPU_PROFILES=("4" "5" "6")

# Common matmul shapes for Llama-family models
# Format: MxNxK (output MxN, reduction K)
SHAPES=(
    "256x256x256"
    "512x512x512"
    "1024x1024x1024"
    "2048x2048x2048"
    "3072x3072x3072"
    "4096x4096x4096"
    "8192x8192x8192"
)

# Additional asymmetric shapes (FFN down projections)
ASYM_SHAPES=(
    "3072x8192x8192"
    "8192x3072x8192"
    "2048x4096x4096"
    "4096x2048x4096"
)

mkdir -p "$XCLBIN_DIR"

echo "=== GGNPU NPU Kernel Builder ==="
echo "Cache dir: $CACHE_DIR"
echo ""

#====//
# Check for required tools
#====//
AIECC_FOUND=false
AIECC_PATH=""

if [ -n "${AIE_HOME:-}" ]; then
    if [ -f "$AIE_HOME/bin/aiecc.py" ]; then
        AIECC_FOUND=true
        AIECC_PATH="$AIE_HOME/bin/aiecc.py"
        echo "  mlir-aie: found at $AIECC_PATH"
    else
        echo "  WARNING: AIE_HOME=$AIE_HOME but aiecc.py not found"
    fi
else
    if command -v aiecc.py >/dev/null 2>&1; then
        AIECC_FOUND=true
        AIECC_PATH="$(command -v aiecc.py)"
        echo "  mlir-aie: found at $AIECC_PATH"
    else
        echo "  WARNING: mlir-aie (aiecc.py) not found"
        echo "  Install mlir-aie or set AIE_HOME"
        echo "  https://github.com/Xilinx/mlir-aie"
    fi
fi

PEANO_FOUND=false
if [ -n "${PEANO_HOME:-}" ]; then
    if [ -f "$PEANO_HOME/bin/aie2p-none-unknown-elf-g++" ]; then
        PEANO_FOUND=true
        echo "  Peano: found at $PEANO_HOME"
    else
        echo "  WARNING: PEANO_HOME=$PEANO_HOME but aie2p-g++ not found"
    fi
elif command -v aie2p-none-unknown-elf-g++ >/dev/null 2>&1; then
    PEANO_FOUND=true
    echo "  Peano: found ($(command -v aie2p-none-unknown-elf-g__))"
else
    echo "  WARNING: Peano (aie2p-g++) not found"
    echo "  Install Peano or set PEANO_HOME"
    echo "  https://github.com/Xilinx/peano"
fi

echo ""

#====//
# Generate MLIR source for a given shape
#====//
generate_mlir() {
    local M="$1"
    local N="$2"
    local K="$3"
    local profile="$4"
    local output_file="$5"

    local tile_m=16
    local tile_n=16
    local vec_w=16
    local num_tiles=8

    cat > "$output_file" << EOF
// GGNPU auto-generated MLIR for INT8 matmul: ${M}x${N}x${K}
// NPU profile: npu${profile}
// Generated by build-kernels.sh

module attributes {aie.device = "aie2p"} {
    // DMA channels
    %dma_a = "aie.dma_acquire"() {
        channel_id = 0 : i32,
        direction = "host_to_tile" : string
    } : () -> !aie.objectbox.stream

    %dma_b = "aie.dma_acquire"() {
        channel_id = 1 : i32,
        direction = "host_to_tile" : string
    } : () -> !aie.objectbox.stream

    %dma_c = "aie.dma_acquire"() {
        channel_id = 2 : i32,
        direction = "tile_to_host" : string
    } : () -> !aie.objectbox.stream

    // Shim tile
    "aie.shimtile"(#aie.tile{row = 0, col = 0}) {
        "aie.dma_port"() { port = "A", direction = "input" } : () -> ()
        "aie.dma_port"() { port = "B", direction = "input" } : () -> ()
        "aie.dma_port"() { port = "C", direction = "output" } : () -> ()
    }

    // Control tile
    "aie.tile"(#aie.tile{row = 0, col = 0}) {
        %lock = "aie.lock"() {
            lock = #aie.lock{lock_id = 3, target = "tile",
                tile = #aie.tile{row = 1, col = 0}}
        } : () -> !aie.lock
        "aie.dma_start"(%dma_a) { len = $((M * K)) : i64 } : (!aie.objectbox.stream) -> ()
        "aie.dma_start"(%dma_b) { len = $((K * N)) : i64 } : (!aie.objectbox.stream) -> ()
        "aie.lock"(%lock) : (!aie.lock) -> ()
        "aie.dma_wait"(%dma_c) { count = 1 : i32 } : (!aie.objectbox.stream) -> ()
    }

    // Compute tiles
EOF

    for ((t=0; t<num_tiles; t++)); do
        cat >> "$output_file" << EOF
    "aie.tile"(#aie.tile{row = 1, col = $t}) {
        %ls = "aie.lock"() {
            lock = #aie.lock{lock_id = 3, target = "tile",
                tile = #aie.tile{row = 1, col = 0}}
        } : () -> !aie.lock
        "aie.lock"(%ls) : (!aie.lock) -> ()
        "aie.unlock"(%ls) : (!aie.lock) -> ()
    }
EOF
    done

    cat >> "$output_file" << EOF
}
EOF
}

#====//
# Compile MLIR to xclbin
#====//
compile_xclbin() {
    local mlir_file="$1"
    local output_xclbin="$2"
    local profile="$3"

    local cmd="$AIECC_PATH --target=aie2p --npu-profile=$profile"

    if [ "$PEANO_FOUND" = true ]; then
        if [ -n "${PEANO_HOME:-}" ]; then
            cmd+=" -I${PEANO_HOME}/include -L${PEANO_HOME}/lib"
        else
            cmd+=" -I$(dirname $(dirname $(which aie2p-none-unknown-elf-g++)))/include"
            cmd+=" -L$(dirname $(dirname $(which aie2p-none-unknown-elf-g++)))/lib"
        fi
    fi

    cmd+=" \"$mlir_file\" -o \"$output_xclbin\""

    echo "    Compiling: $output_xclbin"
    if eval "$cmd" 2>&1; then
        local size=$(stat -c%s "$output_xclbin" 2>/dev/null || echo "unknown")
        echo "    Success: ${size} bytes"
        return 0
    else
        echo "    FAILED"
        return 1
    fi
}

#====//
# Build kernels
#====//
if [ "$AIECC_FOUND" = false ]; then
    echo "Cannot build kernels: mlir-aie not available"
    echo ""
    echo "To install mlir-aie:"
    echo "  git clone https://github.com/Xilinx/mlir-aie.git"
    echo "  cd mlir-aie && mkdir build && cd build"
    echo "  cmake -G Ninja .. -DCMAKE_BUILD_TYPE=Release \\"
    echo "      -DLLVM_ENABLE_PROJECTS=mlir \\"
    echo "      -DMLIR_AIE_BUILD_TOOLS=ON"
    echo "  ninja"
    echo ""
    echo "Or use prebuilt xclbins in ~/.cache/ggnpu/xclbin/"
    exit 1
fi

echo "Building kernels for profiles: ${NPU_PROFILES[*]}"
echo ""

TOTAL=0
SUCCESS=0
FAILED=0

# Build symmetric shapes
for SHAPE in "${SHAPES[@]}"; do
    IFS='x' read -r M N K <<< "$SHAPE"
    TOTAL=$((TOTAL + 1))

    for PROFILE in "${NPU_PROFILES[@]}"; do
        PROFILE_STR="npu${PROFILE}"
        XCLBIN_NAME="matmul_${PROFILE_STR}_${M}x${N}x${K}.xclbin"
        XCLBIN_PATH="$XCLBIN_DIR/$XCLBIN_NAME"

        if [ -f "$XCLBIN_PATH" ]; then
            echo "  $XCLBIN_NAME: already cached, skipping"
            SUCCESS=$((SUCCESS + 1))
            continue
        fi

        MLIR_TMP=$(mktemp /tmp/ggnpu_mlir_XXXXXX.mlir)
        generate_mlir "$M" "$N" "$K" "$PROFILE" "$MLIR_TMP"

        if compile_xclbin "$MLIR_TMP" "$XCLBIN_PATH" "$PROFILE"; then
            SUCCESS=$((SUCCESS + 1))
        else
            FAILED=$((FAILED + 1))
        fi

        rm -f "$MLIR_TMP"
    done
done

# Build asymmetric shapes
for SHAPE in "${ASYM_SHAPES[@]}"; do
    IFS='x' read -r M N K <<< "$SHAPE"
    TOTAL=$((TOTAL + 1))

    for PROFILE in "${NPU_PROFILES[@]}"; do
        PROFILE_STR="npu${PROFILE}"
        XCLBIN_NAME="matmul_${PROFILE_STR}_${M}x${N}x${K}.xclbin"
        XCLBIN_PATH="$XCLBIN_DIR/$XCLBIN_NAME"

        if [ -f "$XCLBIN_PATH" ]; then
            echo "  $XCLBIN_NAME: already cached, skipping"
            SUCCESS=$((SUCCESS + 1))
            continue
        fi

        MLIR_TMP=$(mktemp /tmp/ggnpu_mlir_XXXXXX.mlir)
        generate_mlir "$M" "$N" "$K" "$PROFILE" "$MLIR_TMP"

        if compile_xclbin "$MLIR_TMP" "$XCLBIN_PATH" "$PROFILE"; then
            SUCCESS=$((SUCCESS + 1))
        else
            FAILED=$((FAILED + 1))
        fi

        rm -f "$MLIR_TMP"
    done
done

echo ""
echo "=== Build Summary ==="
echo "  Total: $TOTAL shapes x ${#NPU_PROFILES[@]} profiles"
echo "  Success: $SUCCESS"
echo "  Failed: $FAILED"
echo "  Output: $XCLBIN_DIR"
echo ""
echo "To use prebuilt xclbins, copy them to:"
echo "  ~/.cache/ggnpu/xclbin/"
echo ""
echo "Or set GGNPU_CACHE_DIR to a custom location."
